version: 2

jobs:
  build:
    working_directory: ~/duct.module.bidi
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: nbd
      LC_ALL: C
    steps:
      - checkout
      - restore_cache:
          key: duct.module.bidi-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: duct.module.bidi-{{ checksum "project.clj" }}
      - run: lein coverage
      - run: lein kibit
